/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#ifdef _M_IX86


#define ARCH_AARCH64 0

#define ARCH_ARM 0

#define ARCH_PPC64LE 0

#define ARCH_X86 1

#define ARCH_X86_32 1

#define ARCH_X86_64 0

#define CONFIG_16BPC 1

#define CONFIG_8BPC 1

#define CONFIG_LOG 1

#define ENDIANNESS_BIG 0

#define HAVE_ALIGNED_MALLOC 1

#define HAVE_ASM 1

#define HAVE_AVX512ICL 1

#define HAVE_IO_H 1

#define HAVE_UNISTD_H 1

#define PREFIX 1

#define STACK_ALIGNMENT 16

#define UNICODE 1

#define _CRT_DECLARE_NONSTDC_NAMES 1

#define _FILE_OFFSET_BITS 64

#define _UNICODE 1

#define _WIN32_WINNT 0x0601

#define __USE_MINGW_ANSI_STDIO 1

#else

#define ARCH_AARCH64 0

#define ARCH_ARM 0

#define ARCH_PPC64LE 0

#define ARCH_X86 1

#define ARCH_X86_32 0

#define ARCH_X86_64 1

#define CONFIG_16BPC 1

#define CONFIG_8BPC 1

#define CONFIG_LOG 1

#define ENDIANNESS_BIG 0

#define HAVE_ALIGNED_MALLOC 1

#define HAVE_ASM 1

#define HAVE_AVX512ICL 1

#define HAVE_IO_H 1

#define HAVE_UNISTD_H 1

#define STACK_ALIGNMENT 16

#define UNICODE 1

#define _CRT_DECLARE_NONSTDC_NAMES 1

#define _FILE_OFFSET_BITS 64

#define _UNICODE 1

#define _WIN32_WINNT 0x0601

#define __USE_MINGW_ANSI_STDIO 1

#endif
